# Generated by Django 4.2.5 on 2023-09-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_productmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='img',
            field=models.FileField(upload_to='product'),
        ),
    ]
