# Generated by Django 4.2.5 on 2023-10-04 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_alter_productmodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='favorite_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
